"""epidemiology and model platform

Revision ID: 9c7f6df28fde
Revises: 20260712_0001
Create Date: 2026-07-12 22:51:37.963956
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9c7f6df28fde"
down_revision: str | None = "20260712_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("institution", sa.String(length=160), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("endpoint", sa.String(length=1000), nullable=True),
        sa.Column("dataset_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("refresh_cron", sa.String(length=80), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    op.create_index(
        op.f("ix_data_sources_institution"), "data_sources", ["institution"], unique=False
    )
    op.create_index(
        op.f("ix_data_sources_source_type"), "data_sources", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_data_sources_status"), "data_sources", ["status"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("disease", sa.String(length=40), nullable=False),
        sa.Column("horizon_weeks", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("artifact_uri", sa.String(length=1000), nullable=False),
        sa.Column("training_started_on", sa.Date(), nullable=True),
        sa.Column("training_ended_on", sa.Date(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("feature_names", sa.JSON(), nullable=False),
        sa.Column("data_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("disease", "horizon_weeks", "version", name="uq_model_version"),
    )
    op.create_index(
        "ix_model_active", "model_versions", ["disease", "horizon_weeks", "stage"], unique=False
    )
    op.create_index(op.f("ix_model_versions_disease"), "model_versions", ["disease"], unique=False)
    op.create_index(
        op.f("ix_model_versions_horizon_weeks"), "model_versions", ["horizon_weeks"], unique=False
    )
    op.create_index(op.f("ix_model_versions_stage"), "model_versions", ["stage"], unique=False)
    op.create_table(
        "municipalities",
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("department_code", sa.String(length=2), nullable=False),
        sa.Column("department_name", sa.String(length=120), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("geometry_geojson", sa.JSON(), nullable=True),
        sa.Column("source_vintage", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_municipalities")),
    )
    op.create_index(
        op.f("ix_municipalities_department_code"),
        "municipalities",
        ["department_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipalities_department_name"),
        "municipalities",
        ["department_name"],
        unique=False,
    )
    op.create_index(op.f("ix_municipalities_name"), "municipalities", ["name"], unique=False)
    op.create_index(
        "ix_municipality_department_name",
        "municipalities",
        ["department_code", "name"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_municipalities_location_gist ON municipalities "
            "USING GIST (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)) "
            "WHERE longitude IS NOT NULL AND latitude IS NOT NULL"
        )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("disease", sa.String(length=40), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_week", sa.Date(), nullable=False),
        sa.Column("horizon_weeks", sa.Integer(), nullable=False),
        sa.Column("predicted_cases", sa.Float(), nullable=False),
        sa.Column("interval_lower", sa.Float(), nullable=False),
        sa.Column("interval_upper", sa.Float(), nullable=False),
        sa.Column("outbreak_probability", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("data_completeness", sa.Float(), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("component_predictions", sa.JSON(), nullable=False),
        sa.Column("drivers", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_forecasts_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_forecasts_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
        sa.UniqueConstraint(
            "municipality_code",
            "disease",
            "target_week",
            "horizon_weeks",
            "model_version_id",
            name="uq_forecast_identity",
        ),
    )
    op.create_index(
        "ix_forecast_map", "forecasts", ["disease", "horizon_weeks", "issued_at"], unique=False
    )
    op.create_index(op.f("ix_forecasts_disease"), "forecasts", ["disease"], unique=False)
    op.create_index(
        op.f("ix_forecasts_horizon_weeks"), "forecasts", ["horizon_weeks"], unique=False
    )
    op.create_index(
        op.f("ix_forecasts_model_version_id"), "forecasts", ["model_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_forecasts_municipality_code"), "forecasts", ["municipality_code"], unique=False
    )
    op.create_index(op.f("ix_forecasts_risk_level"), "forecasts", ["risk_level"], unique=False)
    op.create_index(op.f("ix_forecasts_target_week"), "forecasts", ["target_week"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("cursor", sa.String(length=300), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("quality_report", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_ingestion_runs_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_id"), "ingestion_runs", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_status"), "ingestion_runs", ["status"], unique=False)
    op.create_index(
        "ix_ingestion_source_started", "ingestion_runs", ["source_id", "started_at"], unique=False
    )
    op.create_table(
        "model_training_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("disease", sa.String(length=40), nullable=False),
        sa.Column("horizons", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_model_training_runs_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_training_runs")),
    )
    op.create_index(
        op.f("ix_model_training_runs_disease"), "model_training_runs", ["disease"], unique=False
    )
    op.create_index(
        op.f("ix_model_training_runs_status"), "model_training_runs", ["status"], unique=False
    )
    op.create_index(
        "ix_training_disease_created",
        "model_training_runs",
        ["disease", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("forecast_id", sa.String(length=36), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["forecasts.id"],
            name=op.f("fk_alert_events_forecast_id_forecasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_alert_events_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    op.create_index(
        "ix_alert_event_status_created", "alert_events", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_alert_events_forecast_id"), "alert_events", ["forecast_id"], unique=True
    )
    op.create_index(op.f("ix_alert_events_status"), "alert_events", ["status"], unique=False)
    op.create_table(
        "climate_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("temperature_mean_c", sa.Float(), nullable=True),
        sa.Column("humidity_relative_pct", sa.Float(), nullable=True),
        sa.Column("station_count", sa.Integer(), nullable=False),
        sa.Column("interpolation_method", sa.String(length=80), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_climate_observations_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_climate_observations_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_climate_observations_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_climate_observations")),
        sa.UniqueConstraint("municipality_code", "week_start", name="uq_climate_municipality_week"),
    )
    op.create_index(
        op.f("ix_climate_observations_municipality_code"),
        "climate_observations",
        ["municipality_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_climate_observations_source_id"),
        "climate_observations",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_climate_observations_week_start"),
        "climate_observations",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "deforestation_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("deforested_hectares", sa.Float(), nullable=True),
        sa.Column("early_warning_count", sa.Integer(), nullable=True),
        sa.Column("has_active_warning", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_deforestation_observations_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_deforestation_observations_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_deforestation_observations_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deforestation_observations")),
        sa.UniqueConstraint(
            "municipality_code", "year", "quarter", name="uq_deforestation_municipality_period"
        ),
    )
    op.create_index(
        op.f("ix_deforestation_observations_municipality_code"),
        "deforestation_observations",
        ["municipality_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deforestation_observations_source_id"),
        "deforestation_observations",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deforestation_observations_year"),
        "deforestation_observations",
        ["year"],
        unique=False,
    )
    op.create_table(
        "epidemiological_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("disease", sa.String(length=40), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("epidemiological_week", sa.Integer(), nullable=False),
        sa.Column("epidemiological_year", sa.Integer(), nullable=False),
        sa.Column("cases", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("incidence_per_100k", sa.Float(), nullable=True),
        sa.Column("is_preliminary", sa.Boolean(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_epidemiological_observations_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_epidemiological_observations_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_epidemiological_observations_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_epidemiological_observations")),
        sa.UniqueConstraint(
            "municipality_code", "disease", "week_start", name="uq_epi_municipality_disease_week"
        ),
    )
    op.create_index(
        "ix_epi_disease_week",
        "epidemiological_observations",
        ["disease", "week_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epidemiological_observations_disease"),
        "epidemiological_observations",
        ["disease"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epidemiological_observations_ingestion_run_id"),
        "epidemiological_observations",
        ["ingestion_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epidemiological_observations_municipality_code"),
        "epidemiological_observations",
        ["municipality_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epidemiological_observations_source_id"),
        "epidemiological_observations",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epidemiological_observations_week_start"),
        "epidemiological_observations",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "socioeconomic_indicators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("water_access_pct", sa.Float(), nullable=True),
        sa.Column("sewer_access_pct", sa.Float(), nullable=True),
        sa.Column("overcrowding_pct", sa.Float(), nullable=True),
        sa.Column("nbi_pct", sa.Float(), nullable=True),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_socioeconomic_indicators_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_socioeconomic_indicators_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_socioeconomic_indicators_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_socioeconomic_indicators")),
        sa.UniqueConstraint("municipality_code", "year", name="uq_socioeconomic_municipality_year"),
    )
    op.create_index(
        op.f("ix_socioeconomic_indicators_municipality_code"),
        "socioeconomic_indicators",
        ["municipality_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socioeconomic_indicators_source_id"),
        "socioeconomic_indicators",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_socioeconomic_indicators_year"), "socioeconomic_indicators", ["year"], unique=False
    )
    op.create_table(
        "vaccination_coverages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("municipality_code", sa.String(length=5), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("vaccine", sa.String(length=100), nullable=False),
        sa.Column("target_population", sa.Integer(), nullable=True),
        sa.Column("doses_applied", sa.Integer(), nullable=True),
        sa.Column("coverage_pct", sa.Float(), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_vaccination_coverages_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["municipality_code"],
            ["municipalities.code"],
            name=op.f("fk_vaccination_coverages_municipality_code_municipalities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_vaccination_coverages_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vaccination_coverages")),
        sa.UniqueConstraint(
            "municipality_code", "year", "month", "vaccine", name="uq_vax_municipality_period"
        ),
    )
    op.create_index(
        op.f("ix_vaccination_coverages_municipality_code"),
        "vaccination_coverages",
        ["municipality_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vaccination_coverages_source_id"),
        "vaccination_coverages",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vaccination_coverages_vaccine"), "vaccination_coverages", ["vaccine"], unique=False
    )
    op.create_index(
        op.f("ix_vaccination_coverages_year"), "vaccination_coverages", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vaccination_coverages_year"), table_name="vaccination_coverages")
    op.drop_index(op.f("ix_vaccination_coverages_vaccine"), table_name="vaccination_coverages")
    op.drop_index(op.f("ix_vaccination_coverages_source_id"), table_name="vaccination_coverages")
    op.drop_index(
        op.f("ix_vaccination_coverages_municipality_code"), table_name="vaccination_coverages"
    )
    op.drop_table("vaccination_coverages")
    op.drop_index(op.f("ix_socioeconomic_indicators_year"), table_name="socioeconomic_indicators")
    op.drop_index(
        op.f("ix_socioeconomic_indicators_source_id"), table_name="socioeconomic_indicators"
    )
    op.drop_index(
        op.f("ix_socioeconomic_indicators_municipality_code"), table_name="socioeconomic_indicators"
    )
    op.drop_table("socioeconomic_indicators")
    op.drop_index(
        op.f("ix_epidemiological_observations_week_start"),
        table_name="epidemiological_observations",
    )
    op.drop_index(
        op.f("ix_epidemiological_observations_source_id"), table_name="epidemiological_observations"
    )
    op.drop_index(
        op.f("ix_epidemiological_observations_municipality_code"),
        table_name="epidemiological_observations",
    )
    op.drop_index(
        op.f("ix_epidemiological_observations_ingestion_run_id"),
        table_name="epidemiological_observations",
    )
    op.drop_index(
        op.f("ix_epidemiological_observations_disease"), table_name="epidemiological_observations"
    )
    op.drop_index("ix_epi_disease_week", table_name="epidemiological_observations")
    op.drop_table("epidemiological_observations")
    op.drop_index(
        op.f("ix_deforestation_observations_year"), table_name="deforestation_observations"
    )
    op.drop_index(
        op.f("ix_deforestation_observations_source_id"), table_name="deforestation_observations"
    )
    op.drop_index(
        op.f("ix_deforestation_observations_municipality_code"),
        table_name="deforestation_observations",
    )
    op.drop_table("deforestation_observations")
    op.drop_index(op.f("ix_climate_observations_week_start"), table_name="climate_observations")
    op.drop_index(op.f("ix_climate_observations_source_id"), table_name="climate_observations")
    op.drop_index(
        op.f("ix_climate_observations_municipality_code"), table_name="climate_observations"
    )
    op.drop_table("climate_observations")
    op.drop_index(op.f("ix_alert_events_status"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_forecast_id"), table_name="alert_events")
    op.drop_index("ix_alert_event_status_created", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index("ix_training_disease_created", table_name="model_training_runs")
    op.drop_index(op.f("ix_model_training_runs_status"), table_name="model_training_runs")
    op.drop_index(op.f("ix_model_training_runs_disease"), table_name="model_training_runs")
    op.drop_table("model_training_runs")
    op.drop_index("ix_ingestion_source_started", table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_status"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_source_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_forecasts_target_week"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_risk_level"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_municipality_code"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_model_version_id"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_horizon_weeks"), table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_disease"), table_name="forecasts")
    op.drop_index("ix_forecast_map", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index("ix_municipality_department_name", table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_name"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_department_name"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_department_code"), table_name="municipalities")
    op.drop_table("municipalities")
    op.drop_index(op.f("ix_model_versions_stage"), table_name="model_versions")
    op.drop_index(op.f("ix_model_versions_horizon_weeks"), table_name="model_versions")
    op.drop_index(op.f("ix_model_versions_disease"), table_name="model_versions")
    op.drop_index("ix_model_active", table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_data_sources_status"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_source_type"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_institution"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
